version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/postgres
    volumes:
      - postgres:/data/postgres
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  ms-book:
    build:
      context: ./apigolang
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./apigolang:/app
    env_file:
      - postgres.env
    environment:
      - PORT=3003

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/var/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
volumes:
  postgres:
  pgadmin:
